#QT -= gui
#CONFIG += qtest
#SOURCES += test_mpd_utils.cpp ../mpd_utils.cpp
#HEADERS += test_mpd_utils.cpp ../mpd_utils.hpp

######################################################################
# Automatically generated by qmake (2.01a) fre. feb. 26 21:44:01 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../mpd/mpd_utils.hpp
SOURCES += test_mpd_utils.cpp test_mpd_utils.moc ../mpd/mpd_utils.cpp
